# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\martin.schoreisz\.qgis2\python\plugins\Mizogeo\fenetre_menu_Agregation.ui'
#
# Created: Fri Jun 02 15:50:46 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_Agregation(object):
    def setupUi(self, Dialog_Agregation):
        Dialog_Agregation.setObjectName(_fromUtf8("Dialog_Agregation"))
        Dialog_Agregation.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_Agregation.resize(800, 550)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(11)
        Dialog_Agregation.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog_Agregation)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_Zbr = QtGui.QGroupBox(Dialog_Agregation)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox_Zbr.setFont(font)
        self.groupBox_Zbr.setObjectName(_fromUtf8("groupBox_Zbr"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_Zbr)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setContentsMargins(20, 12, 30, 15)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.line_Zbr = QtGui.QLineEdit(self.groupBox_Zbr)
        self.line_Zbr.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Zbr.sizePolicy().hasHeightForWidth())
        self.line_Zbr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.line_Zbr.setFont(font)
        self.line_Zbr.setObjectName(_fromUtf8("line_Zbr"))
        self.horizontalLayout.addWidget(self.line_Zbr)
        self.Btn_Zbr = QtGui.QToolButton(self.groupBox_Zbr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Zbr.sizePolicy().hasHeightForWidth())
        self.Btn_Zbr.setSizePolicy(sizePolicy)
        self.Btn_Zbr.setMinimumSize(QtCore.QSize(70, 30))
        self.Btn_Zbr.setMaximumSize(QtCore.QSize(70, 30))
        self.Btn_Zbr.setAutoRaise(False)
        self.Btn_Zbr.setObjectName(_fromUtf8("Btn_Zbr"))
        self.horizontalLayout.addWidget(self.Btn_Zbr)
        self.verticalLayout.addWidget(self.groupBox_Zbr)
        self.groupBox_administratif = QtGui.QGroupBox(Dialog_Agregation)
        self.groupBox_administratif.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox_administratif.setFont(font)
        self.groupBox_administratif.setObjectName(_fromUtf8("groupBox_administratif"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_administratif)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setContentsMargins(20, 12, 30, 15)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.line_DepartementPpbe = QtGui.QLineEdit(self.groupBox_administratif)
        self.line_DepartementPpbe.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_DepartementPpbe.sizePolicy().hasHeightForWidth())
        self.line_DepartementPpbe.setSizePolicy(sizePolicy)
        self.line_DepartementPpbe.setMinimumSize(QtCore.QSize(0, 0))
        self.line_DepartementPpbe.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.line_DepartementPpbe.setFont(font)
        self.line_DepartementPpbe.setObjectName(_fromUtf8("line_DepartementPpbe"))
        self.listWidget_departementPpbe = QtGui.QListWidget(self.groupBox_administratif)
        self.listWidget_departementPpbe.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.listWidget_departementPpbe.setObjectName(_fromUtf8("listWidget_departementPpbe"))
        self.horizontalLayout_4.addWidget(self.listWidget_departementPpbe)
        self.horizontalLayout_4.addWidget(self.line_DepartementPpbe)
        self.verticalLayout.addWidget(self.groupBox_administratif)
        self.groupBox_perimetre = QtGui.QGroupBox(Dialog_Agregation)
        self.groupBox_perimetre.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox_perimetre.setFont(font)
        self.groupBox_perimetre.setObjectName(_fromUtf8("groupBox_perimetre"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_perimetre)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setContentsMargins(20, 12, 30, 15)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.line_perimetre = QtGui.QLineEdit(self.groupBox_perimetre)
        self.line_perimetre.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_perimetre.sizePolicy().hasHeightForWidth())
        self.line_perimetre.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.line_perimetre.setFont(font)
        self.line_perimetre.setReadOnly(False)
        self.line_perimetre.setObjectName(_fromUtf8("line_perimetre"))
        self.horizontalLayout_2.addWidget(self.line_perimetre)
        self.Btn_perimetre = QtGui.QToolButton(self.groupBox_perimetre)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_perimetre.sizePolicy().hasHeightForWidth())
        self.Btn_perimetre.setSizePolicy(sizePolicy)
        self.Btn_perimetre.setMinimumSize(QtCore.QSize(70, 30))
        self.Btn_perimetre.setMaximumSize(QtCore.QSize(70, 30))
        self.Btn_perimetre.setObjectName(_fromUtf8("Btn_perimetre"))
        self.horizontalLayout_2.addWidget(self.Btn_perimetre)
        self.verticalLayout.addWidget(self.groupBox_perimetre)
        self.groupBox_Sortie = QtGui.QGroupBox(Dialog_Agregation)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox_Sortie.setFont(font)
        self.groupBox_Sortie.setObjectName(_fromUtf8("groupBox_Sortie"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_Sortie)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setContentsMargins(20, 12, 30, 15)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.line_Sortie = QtGui.QLineEdit(self.groupBox_Sortie)
        self.line_Sortie.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Sortie.sizePolicy().hasHeightForWidth())
        self.line_Sortie.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.line_Sortie.setFont(font)
        self.line_Sortie.setAutoFillBackground(False)
        self.line_Sortie.setStyleSheet(_fromUtf8(""))
        self.line_Sortie.setObjectName(_fromUtf8("line_Sortie"))
        self.horizontalLayout_3.addWidget(self.line_Sortie)
        self.Btn_ChoixSortie = QtGui.QToolButton(self.groupBox_Sortie)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_ChoixSortie.sizePolicy().hasHeightForWidth())
        self.Btn_ChoixSortie.setSizePolicy(sizePolicy)
        self.Btn_ChoixSortie.setMinimumSize(QtCore.QSize(70, 30))
        self.Btn_ChoixSortie.setMaximumSize(QtCore.QSize(70, 30))
        self.Btn_ChoixSortie.setObjectName(_fromUtf8("Btn_ChoixSortie"))
        self.horizontalLayout_3.addWidget(self.Btn_ChoixSortie)
        self.verticalLayout.addWidget(self.groupBox_Sortie)
        self.ButtonBox_Final = QtGui.QDialogButtonBox(Dialog_Agregation)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.ButtonBox_Final.setFont(font)
        self.ButtonBox_Final.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.ButtonBox_Final.setObjectName(_fromUtf8("ButtonBox_Final"))
        self.verticalLayout.addWidget(self.ButtonBox_Final)

        self.retranslateUi(Dialog_Agregation)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Agregation)

    def retranslateUi(self, Dialog_Agregation):
        Dialog_Agregation.setWindowTitle(_translate("Dialog_Agregation", "Agrégation de fichiers N_BRUIT_ZBR par périmètre", None))
        self.groupBox_Zbr.setTitle(_translate("Dialog_Agregation", "Dossier contenant les fichiers N_BRUIT_ZBR", None))
        self.line_Zbr.setToolTip(_translate("Dialog_Agregation", "Copier/coller l'emplacement des fichiers N_BRUIT_ZBR au format Géostandard - dossier", None))
        self.line_Zbr.setPlaceholderText(_translate("Dialog_Agregation", "Emplacement du dossier contenant les fichiers N_BRUIT_ZBR", None))
        self.Btn_Zbr.setToolTip(_translate("Dialog_Agregation", "Rechercher le dossier contenant les fichiers .shp - dossier", None))
        self.Btn_Zbr.setText(_translate("Dialog_Agregation", "...", None))
        self.groupBox_administratif.setTitle(_translate("Dialog_Agregation", "Département comme périmètre d'agrégation", None))
        self.line_DepartementPpbe.setToolTip(_translate("Dialog_Agregation", "Sélectionner le département d'agrégation", None))
        self.line_DepartementPpbe.setPlaceholderText(_translate("Dialog_Agregation", "Choix du département comme périmètre d'agrégation", None))
        self.listWidget_departementPpbe.setToolTip(_translate("Dialog_Agregation", "Sélectionner/désélectionner par simple clic - un seul choix", None))
        self.groupBox_perimetre.setTitle(_translate("Dialog_Agregation", "Fichier contenant le périmètre d'agrégation", None))
        self.line_perimetre.setToolTip(_translate("Dialog_Agregation", "Copier/coller l'emplacement du fichier périmètre - fichier .shp", None))
        self.line_perimetre.setPlaceholderText(_translate("Dialog_Agregation", "Emplacement du fichier périmètre d'agrégation", None))
        self.Btn_perimetre.setToolTip(_translate("Dialog_Agregation", "Rechercher le fichier périmètre - fichier .shp", None))
        self.Btn_perimetre.setText(_translate("Dialog_Agregation", "...", None))
        self.groupBox_Sortie.setTitle(_translate("Dialog_Agregation", "Dossier de stockage des fichiers agrégés", None))
        self.line_Sortie.setToolTip(_translate("Dialog_Agregation", "Copier/coller l'emplacement où seront stockés les fichiers agrégés - dossier", None))
        self.line_Sortie.setPlaceholderText(_translate("Dialog_Agregation", "Choisir le dossier recevant les fichiers agrégés", None))
        self.Btn_ChoixSortie.setToolTip(_translate("Dialog_Agregation", "Rechercher le dossier de stockage des fichiers agrégés .shp - dossier", None))
        self.Btn_ChoixSortie.setText(_translate("Dialog_Agregation", "...", None))

