# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\martin.schoreisz\.qgis2\python\plugins\Mizogeo\fenetre_menu_ZBR_CBS.ui'
#
# Created: Fri Jun 16 10:44:01 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_ZbrCbs(object):
    def setupUi(self, Dialog_ZbrCbs):
        Dialog_ZbrCbs.setObjectName(_fromUtf8("Dialog_ZbrCbs"))
        Dialog_ZbrCbs.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_ZbrCbs.resize(800, 500)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_ZbrCbs.sizePolicy().hasHeightForWidth())
        Dialog_ZbrCbs.setSizePolicy(sizePolicy)
        Dialog_ZbrCbs.setMinimumSize(QtCore.QSize(800, 500))
        Dialog_ZbrCbs.setMaximumSize(QtCore.QSize(1600, 1000))
        Dialog_ZbrCbs.setSizeIncrement(QtCore.QSize(0, 0))
        Dialog_ZbrCbs.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        Dialog_ZbrCbs.setFont(font)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog_ZbrCbs)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setMargin(9)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_dossierIsophones = QtGui.QGroupBox(Dialog_ZbrCbs)
        self.groupBox_dossierIsophones.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_dossierIsophones.sizePolicy().hasHeightForWidth())
        self.groupBox_dossierIsophones.setSizePolicy(sizePolicy)
        self.groupBox_dossierIsophones.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox_dossierIsophones.setFont(font)
        self.groupBox_dossierIsophones.setCheckable(False)
        self.groupBox_dossierIsophones.setObjectName(_fromUtf8("groupBox_dossierIsophones"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_dossierIsophones)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(20, 12, 30, 15)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.line_isophone = QtGui.QLineEdit(self.groupBox_dossierIsophones)
        self.line_isophone.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_isophone.sizePolicy().hasHeightForWidth())
        self.line_isophone.setSizePolicy(sizePolicy)
        self.line_isophone.setMinimumSize(QtCore.QSize(640, 30))
        self.line_isophone.setMaximumSize(QtCore.QSize(1280, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.line_isophone.setFont(font)
        self.line_isophone.setText(_fromUtf8(""))
        self.line_isophone.setObjectName(_fromUtf8("line_isophone"))
        self.horizontalLayout.addWidget(self.line_isophone)
        self.Btn_ChoixIsophones = QtGui.QToolButton(self.groupBox_dossierIsophones)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_ChoixIsophones.sizePolicy().hasHeightForWidth())
        self.Btn_ChoixIsophones.setSizePolicy(sizePolicy)
        self.Btn_ChoixIsophones.setMinimumSize(QtCore.QSize(70, 30))
        self.Btn_ChoixIsophones.setMaximumSize(QtCore.QSize(70, 30))
        self.Btn_ChoixIsophones.setAutoRepeatInterval(100)
        self.Btn_ChoixIsophones.setObjectName(_fromUtf8("Btn_ChoixIsophones"))
        self.horizontalLayout.addWidget(self.Btn_ChoixIsophones)
        self.verticalLayout.addWidget(self.groupBox_dossierIsophones)
        self.groupBox_correspondanceVc = QtGui.QGroupBox(Dialog_ZbrCbs)
        self.groupBox_correspondanceVc.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_correspondanceVc.sizePolicy().hasHeightForWidth())
        self.groupBox_correspondanceVc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox_correspondanceVc.setFont(font)
        self.groupBox_correspondanceVc.setObjectName(_fromUtf8("groupBox_correspondanceVc"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_correspondanceVc)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setContentsMargins(20, 12, 30, 15)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.line_CorrespondanceVc = QtGui.QLineEdit(self.groupBox_correspondanceVc)
        self.line_CorrespondanceVc.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_CorrespondanceVc.sizePolicy().hasHeightForWidth())
        self.line_CorrespondanceVc.setSizePolicy(sizePolicy)
        self.line_CorrespondanceVc.setMinimumSize(QtCore.QSize(640, 30))
        self.line_CorrespondanceVc.setMaximumSize(QtCore.QSize(1280, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.line_CorrespondanceVc.setFont(font)
        self.line_CorrespondanceVc.setObjectName(_fromUtf8("line_CorrespondanceVc"))
        self.horizontalLayout_2.addWidget(self.line_CorrespondanceVc)
        self.Btn_ChoixCorrespondanceVc = QtGui.QToolButton(self.groupBox_correspondanceVc)
        self.Btn_ChoixCorrespondanceVc.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_ChoixCorrespondanceVc.sizePolicy().hasHeightForWidth())
        self.Btn_ChoixCorrespondanceVc.setSizePolicy(sizePolicy)
        self.Btn_ChoixCorrespondanceVc.setMinimumSize(QtCore.QSize(70, 30))
        self.Btn_ChoixCorrespondanceVc.setMaximumSize(QtCore.QSize(70, 30))
        self.Btn_ChoixCorrespondanceVc.setObjectName(_fromUtf8("Btn_ChoixCorrespondanceVc"))
        self.horizontalLayout_2.addWidget(self.Btn_ChoixCorrespondanceVc)
        self.verticalLayout.addWidget(self.groupBox_correspondanceVc)
        self.groupBox_VoiesNouvelles = QtGui.QGroupBox(Dialog_ZbrCbs)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox_VoiesNouvelles.setFont(font)
        self.groupBox_VoiesNouvelles.setObjectName(_fromUtf8("groupBox_VoiesNouvelles"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_VoiesNouvelles)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setContentsMargins(20, 12, 30, 15)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.line_VoiesNouvelles = QtGui.QLineEdit(self.groupBox_VoiesNouvelles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_VoiesNouvelles.sizePolicy().hasHeightForWidth())
        self.line_VoiesNouvelles.setSizePolicy(sizePolicy)
        self.line_VoiesNouvelles.setMinimumSize(QtCore.QSize(640, 30))
        self.line_VoiesNouvelles.setMaximumSize(QtCore.QSize(1280, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.line_VoiesNouvelles.setFont(font)
        self.line_VoiesNouvelles.setText(_fromUtf8(""))
        self.line_VoiesNouvelles.setObjectName(_fromUtf8("line_VoiesNouvelles"))
        self.horizontalLayout_3.addWidget(self.line_VoiesNouvelles)
        self.Btn_VoiesNouvelles = QtGui.QToolButton(self.groupBox_VoiesNouvelles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_VoiesNouvelles.sizePolicy().hasHeightForWidth())
        self.Btn_VoiesNouvelles.setSizePolicy(sizePolicy)
        self.Btn_VoiesNouvelles.setMinimumSize(QtCore.QSize(70, 30))
        self.Btn_VoiesNouvelles.setMaximumSize(QtCore.QSize(70, 30))
        self.Btn_VoiesNouvelles.setObjectName(_fromUtf8("Btn_VoiesNouvelles"))
        self.horizontalLayout_3.addWidget(self.Btn_VoiesNouvelles)
        self.verticalLayout.addWidget(self.groupBox_VoiesNouvelles)
        self.groupBox_Sortie = QtGui.QGroupBox(Dialog_ZbrCbs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Sortie.sizePolicy().hasHeightForWidth())
        self.groupBox_Sortie.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox_Sortie.setFont(font)
        self.groupBox_Sortie.setObjectName(_fromUtf8("groupBox_Sortie"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_Sortie)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setContentsMargins(20, 12, 30, 15)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.line_Sortie = QtGui.QLineEdit(self.groupBox_Sortie)
        self.line_Sortie.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Sortie.sizePolicy().hasHeightForWidth())
        self.line_Sortie.setSizePolicy(sizePolicy)
        self.line_Sortie.setMinimumSize(QtCore.QSize(640, 30))
        self.line_Sortie.setMaximumSize(QtCore.QSize(1280, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.line_Sortie.setFont(font)
        self.line_Sortie.setAutoFillBackground(False)
        self.line_Sortie.setStyleSheet(_fromUtf8(""))
        self.line_Sortie.setObjectName(_fromUtf8("line_Sortie"))
        self.horizontalLayout_4.addWidget(self.line_Sortie)
        self.Btn_ChoixSortie = QtGui.QToolButton(self.groupBox_Sortie)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_ChoixSortie.sizePolicy().hasHeightForWidth())
        self.Btn_ChoixSortie.setSizePolicy(sizePolicy)
        self.Btn_ChoixSortie.setMinimumSize(QtCore.QSize(70, 30))
        self.Btn_ChoixSortie.setMaximumSize(QtCore.QSize(70, 30))
        self.Btn_ChoixSortie.setSizeIncrement(QtCore.QSize(0, 0))
        self.Btn_ChoixSortie.setObjectName(_fromUtf8("Btn_ChoixSortie"))
        self.horizontalLayout_4.addWidget(self.Btn_ChoixSortie)
        self.verticalLayout.addWidget(self.groupBox_Sortie)
        self.groupBox_Producteur = QtGui.QGroupBox(Dialog_ZbrCbs)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox_Producteur.setFont(font)
        self.groupBox_Producteur.setObjectName(_fromUtf8("groupBox_Producteur"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_Producteur)
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setContentsMargins(20, 12, 30, 15)
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.line_Producteur = QtGui.QLineEdit(self.groupBox_Producteur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Producteur.sizePolicy().hasHeightForWidth())
        self.line_Producteur.setSizePolicy(sizePolicy)
        self.line_Producteur.setMinimumSize(QtCore.QSize(640, 30))
        self.line_Producteur.setMaximumSize(QtCore.QSize(1280, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri Light"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.line_Producteur.setFont(font)
        self.line_Producteur.setObjectName(_fromUtf8("line_Producteur"))
        self.horizontalLayout_5.addWidget(self.line_Producteur)
        self.verticalLayout.addWidget(self.groupBox_Producteur)
        self.ButtonBox_Final = QtGui.QDialogButtonBox(Dialog_ZbrCbs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonBox_Final.sizePolicy().hasHeightForWidth())
        self.ButtonBox_Final.setSizePolicy(sizePolicy)
        self.ButtonBox_Final.setSizeIncrement(QtCore.QSize(0, 0))
        self.ButtonBox_Final.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.ButtonBox_Final.setObjectName(_fromUtf8("ButtonBox_Final"))
        self.verticalLayout.addWidget(self.ButtonBox_Final)

        self.retranslateUi(Dialog_ZbrCbs)
        QtCore.QMetaObject.connectSlotsByName(Dialog_ZbrCbs)

    def retranslateUi(self, Dialog_ZbrCbs):
        Dialog_ZbrCbs.setWindowTitle(_translate("Dialog_ZbrCbs", "Création simultanée des fichiers N_BRUIT_ZBR et N_BRUIT_CBS", None))
        self.groupBox_dossierIsophones.setTitle(_translate("Dialog_ZbrCbs", "Dossier contenant les isophones à mettre au Géostandard", None))
        self.line_isophone.setToolTip(_translate("Dialog_ZbrCbs", "Copier/coller l'emplacement des fichiers isophones - dossier", None))
        self.line_isophone.setPlaceholderText(_translate("Dialog_ZbrCbs", "Emplacement du dossier contenant les fichiers isophones à mettre au GéoStandard", None))
        self.Btn_ChoixIsophones.setToolTip(_translate("Dialog_ZbrCbs", "Rechercher le dossier contenant les fichiers .shp/.mif/.tab - dossier", None))
        self.Btn_ChoixIsophones.setText(_translate("Dialog_ZbrCbs", "...", None))
        self.groupBox_correspondanceVc.setTitle(_translate("Dialog_ZbrCbs", "Fichier de correspondance entre le nom du fichier SIG et le nom du rapportage UE", None))
        self.line_CorrespondanceVc.setToolTip(_translate("Dialog_ZbrCbs", "Copier/coller l'emplacement du tableau de correspondance - fichier .csv", None))
        self.line_CorrespondanceVc.setPlaceholderText(_translate("Dialog_ZbrCbs", "Emplacement du fichier correspondant au tableau de correspondance", None))
        self.Btn_ChoixCorrespondanceVc.setToolTip(_translate("Dialog_ZbrCbs", "Rechercher le fichier correspondant au tableau de correspondance entre nom fichier SIG et nom rapportage - fichier .csv", None))
        self.Btn_ChoixCorrespondanceVc.setText(_translate("Dialog_ZbrCbs", "...", None))
        self.groupBox_VoiesNouvelles.setTitle(_translate("Dialog_ZbrCbs", "Fichier de recensement des voies nouvelles", None))
        self.line_VoiesNouvelles.setToolTip(_translate("Dialog_ZbrCbs", "Copier/coller l'emplacement du fichier de recensement - fichier .csv", None))
        self.line_VoiesNouvelles.setPlaceholderText(_translate("Dialog_ZbrCbs", "Emplacement du fichier correspondant au tableau de recensement", None))
        self.Btn_VoiesNouvelles.setToolTip(_translate("Dialog_ZbrCbs", "Rechercher le fichier correspondant au tableau de recensement - fichier .csv", None))
        self.Btn_VoiesNouvelles.setText(_translate("Dialog_ZbrCbs", "...", None))
        self.groupBox_Sortie.setTitle(_translate("Dialog_ZbrCbs", "Dossier de stockage de l'arborescence et des fichiers GéoStandard", None))
        self.line_Sortie.setToolTip(_translate("Dialog_ZbrCbs", "Copier/coller l'emplacement où seront stockés les fichiers GéoStandardisés - dossier", None))
        self.line_Sortie.setPlaceholderText(_translate("Dialog_ZbrCbs", "Emplacement du dossier recevant les fichiers GéoStandardisés", None))
        self.Btn_ChoixSortie.setToolTip(_translate("Dialog_ZbrCbs", "Rechercher le dossier de stockage des fichiers GéoStandardisés .shp - dossier", None))
        self.Btn_ChoixSortie.setText(_translate("Dialog_ZbrCbs", "...", None))
        self.groupBox_Producteur.setTitle(_translate("Dialog_ZbrCbs", "Producteur", None))
        self.line_Producteur.setToolTip(_translate("Dialog_ZbrCbs", "Renseigner le numéro SIREN de l'organisme ayant produit la donnée", None))
        self.line_Producteur.setPlaceholderText(_translate("Dialog_ZbrCbs", "Valeur par défaut : numéro Siren du Cerema", None))

